# Generated by Django 3.2.16 on 2023-02-17 06:56

import custom_reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customreport',
            name='selected_fields',
            field=models.JSONField(default=custom_reports.models.get_json_default, help_text='List of selected fields name'),
        ),
    ]
