# Generated by Django 3.2.16 on 2023-01-31 06:51

from django.db import migrations, models
import django.db.models.deletion
import scheduling.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0017_rename_featuresenalbled_featuresenabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleProviderCreds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendly', models.JSONField(blank=True, default=scheduling.models.get_json_default, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
