# Generated by Django 3.2.16 on 2023-02-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_webhooktestdata_msg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleProviderCreds',
        ),
    ]
