# Generated by Django 3.2.9 on 2022-05-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilogsmodel',
            name='api',
            field=models.CharField(help_text='API URL', max_length=1024),
        ),
    ]
