# Generated by Django 3.2.9 on 2022-05-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0002_alter_apilogsmodel_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogsmodel',
            name='user',
            field=models.CharField(default=1, help_text='API USER', max_length=1024),
            preserve_default=False,
        ),
    ]
