# Generated by Django 3.2.9 on 2021-12-21 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20211220_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='form.form'),
        ),
    ]
