# Generated by Django 3.2.9 on 2021-12-29 06:03

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('form', '0008_formdata_historicalformdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='field_company', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfield',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='field',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['field_name', 'company']),
        ),
        migrations.AlterField(
            model_name='form',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='form_company', to='company.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['form_name', 'company']),
        ),
        migrations.AlterField(
            model_name='historicalfield',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['field_name', 'company']),
        ),
        migrations.AlterField(
            model_name='historicalform',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['form_name', 'company']),
        ),
    ]
