# Generated by Django 3.2.9 on 2022-01-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20220120_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Sort by'),
        ),
        migrations.AddField(
            model_name='fieldchoice',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Sort by'),
        ),
        migrations.AddField(
            model_name='historicalfield',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Sort by'),
        ),
        migrations.AddField(
            model_name='historicalfieldchoice',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Sort by'),
        ),
    ]
