# Generated by Django 3.2.9 on 2022-02-02 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20220113_0515'),
        ('form', '0012_auto_20220131_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpositionapproval',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='positionapproval',
            name='employee',
        ),
        migrations.AddField(
            model_name='historicalpositionapproval',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='employee profile who are going to approve this position', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile'),
        ),
        migrations.AddField(
            model_name='positionapproval',
            name='profile',
            field=models.ForeignKey(default=1, help_text='employee profile who are going to approve this position', on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
            preserve_default=False,
        ),
    ]
