# Generated by Django 3.2.9 on 2022-02-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_auto_20220202_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('closed', 'closed')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalformdata',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('closed', 'closed')], default='draft', max_length=10),
        ),
    ]
