# Generated by Django 3.2.9 on 2022-02-04 06:03

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_auto_20220203_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['form', 'company']),
        ),
        migrations.AddField(
            model_name='historicalformdata',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['form', 'company']),
        ),
    ]
