# Generated by Django 3.2.9 on 2022-02-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_auto_20220204_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='historicalformdata',
            name='slug',
        ),
    ]
