# Generated by Django 3.2.9 on 2022-02-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_auto_20220215_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='candidate_visibility_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='employee_visibility_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalformdata',
            name='candidate_visibility_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalformdata',
            name='employee_visibility_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
