# Generated by Django 3.2.9 on 2022-03-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_historicaljobcategory_jobcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljobcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
