# Generated by Django 3.2.9 on 2022-03-07 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220113_0515'),
        ('form', '0022_auto_20220302_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljobcategory',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose job category company name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Choose job category company name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_category_company', to='company.company'),
        ),
    ]
