# Generated by Django 3.2.9 on 2022-03-08 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0014_auto_20220113_0515'),
        ('company', '0003_auto_20220113_0515'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0023_auto_20220307_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ManyToManyField(blank=True, help_text='Choose your city', to='primary_data.City')),
                ('company', models.ForeignKey(blank=True, help_text='Choose job location for specific company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_location_company', to='company.company')),
                ('country', models.ForeignKey(blank=True, help_text='Choose your Country', null=True, on_delete=django.db.models.deletion.CASCADE, to='primary_data.country')),
                ('state', models.ManyToManyField(blank=True, help_text='Choose your State', to='primary_data.State')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalJobLocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, help_text='Choose job location for specific company', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company')),
                ('country', models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your Country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.country')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical job location',
                'db_table': 'job_location_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
