# Generated by Django 3.2.9 on 2022-03-09 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220113_0515'),
        ('user', '0016_auto_20220113_0515'),
        ('form', '0024_historicaljoblocation_joblocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentViewJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Choose job location for specific company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recent_view_job_company', to='company.company')),
                ('form_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formdata')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
