# Generated by Django 3.2.9 on 2022-03-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0025_recentviewjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljoblocation',
            name='country_image',
            field=models.TextField(blank=True, help_text='Select file', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joblocation',
            name='country_image',
            field=models.FileField(blank=True, help_text='Select file', null=True, upload_to='media/'),
        ),
    ]
