# Generated by Django 3.2.9 on 2022-03-11 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20220113_0515'),
        ('form', '0026_auto_20220309_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='cloned_from_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='created_by_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='form_created_by_profile', to='user.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='is_cloned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalform',
            name='cloned_from_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalform',
            name='created_by_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile'),
        ),
        migrations.AddField(
            model_name='historicalform',
            name='is_cloned',
            field=models.BooleanField(default=False),
        ),
    ]
