# Generated by Django 3.2.9 on 2022-03-14 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_profile_profile_id'),
        ('company', '0003_auto_20220113_0515'),
        ('form', '0027_auto_20220311_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Choose job location for specific company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_position_company', to='company.company')),
                ('form_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formdata')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PositionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Choose company for specific profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_alert_company', to='company.company')),
                ('job_category', models.ManyToManyField(blank=True, to='form.JobCategory')),
                ('job_location', models.ManyToManyField(blank=True, to='form.JobLocation')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
