# Generated by Django 3.2.9 on 2022-03-14 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_profile_profile_id'),
        ('form', '0028_positionalert_savedposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalformdata',
            old_name='profile',
            new_name='created_by_profile',
        ),
        migrations.RemoveField(
            model_name='form',
            name='cloned_from_id',
        ),
        migrations.RemoveField(
            model_name='form',
            name='created_by_profile',
        ),
        migrations.RemoveField(
            model_name='form',
            name='is_cloned',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='historicalform',
            name='cloned_from_id',
        ),
        migrations.RemoveField(
            model_name='historicalform',
            name='created_by_profile',
        ),
        migrations.RemoveField(
            model_name='historicalform',
            name='is_cloned',
        ),
        migrations.AddField(
            model_name='formdata',
            name='cloned_from_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='created_by_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='form_created_by_profile', to='user.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formdata',
            name='is_cloned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalformdata',
            name='cloned_from_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalformdata',
            name='is_cloned',
            field=models.BooleanField(default=False),
        ),
    ]
