# Generated by Django 3.2.9 on 2022-03-16 07:53

from django.db import migrations, models
import django.db.models.deletion
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20220315_0606'),
        ('company', '0004_delete_historicalcompany'),
        ('form', '0030_auto_20220315_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=form.models.contact_default)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('company', models.ForeignKey(blank=True, help_text='Choose job location for specific company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_position_company', to='company.company')),
                ('form_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formdata')),
            ],
        ),
    ]
