# Generated by Django 3.2.9 on 2022-03-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0031_appliedposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerapproval',
            name='approval_type',
            field=models.CharField(choices=[('All at once', 'a-a-o'), ('one to one', 'o-t-o')], default='a-a-o', max_length=11),
        ),
        migrations.AddField(
            model_name='offerapproval',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Sort by'),
        ),
        migrations.AddField(
            model_name='positionapproval',
            name='approval_type',
            field=models.CharField(choices=[('All at once', 'a-a-o'), ('one to one', 'o-t-o')], default='a-a-o', max_length=11),
        ),
        migrations.AddField(
            model_name='positionapproval',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Sort by'),
        ),
    ]
