# Generated by Django 3.2.9 on 2022-03-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20220315_0606'),
        ('form', '0032_auto_20220317_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedposition',
            name='refereed_by_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='refereed_by_profile', to='user.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appliedposition',
            name='applied_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_profile', to='user.profile'),
        ),
    ]
