# Generated by Django 3.2.9 on 2022-04-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0034_alter_appliedposition_refereed_by_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(help_text='1.Onhold, 2.Close, 3.Reject, 4.Approve')),
                ('reason', models.CharField(help_text='Enter your Education', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date and time', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date and time', null=True)),
            ],
        ),
    ]
