# Generated by Django 3.2.9 on 2022-04-25 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_department'),
        ('form', '0035_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reason_company', to='company.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reason',
            name='type',
            field=models.CharField(choices=[('Onhold', 'Onhold'), ('Close', 'Close'), ('Reject', 'Reject'), ('Approve', 'Approve')], default='Onhold', max_length=15),
        ),
    ]
