# Generated by Django 3.2.9 on 2022-05-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0036_auto_20220425_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='type',
            field=models.CharField(choices=[('Onhold', 'Onhold'), ('Close', 'Close'), ('Reject', 'Reject'), ('Approve', 'Approve'), ('Position Rejection', 'position_r'), ('Offer Rejection', 'offer_r'), ('Candidate Rejection', 'candidate_r'), ('Position Hold', 'position_h'), ('Offer Hold', 'offer_h'), ('Candidate Hold', 'candidate_h')], default='Onhold', max_length=50),
        ),
    ]
