# Generated by Django 3.2.13 on 2022-05-17 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_activitylogs_type_id'),
        ('form', '0038_alter_reason_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='created_by_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_created_by_profile', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_form_data', to='form.form'),
        ),
    ]
