# Generated by Django 3.2.13 on 2022-05-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_activitylogs_type_id'),
        ('form', '0040_auto_20220519_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerapproval',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='positionapproval',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offerapproval',
            name='approval_type',
            field=models.CharField(blank=True, choices=[('All at once', 'a-a-o'), ('one to one', 'o-t-o')], default='a-a-o', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='offerapproval',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.formdata'),
        ),
        migrations.AlterField(
            model_name='offerapproval',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='employee profile who are going to approve this position', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AlterField(
            model_name='offerapproval',
            name='sort_order',
            field=models.IntegerField(blank=True, default=1, help_text='Sort by', null=True),
        ),
    ]
