# Generated by Django 3.2.13 on 2022-05-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0041_auto_20220519_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionapproval',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.reason'),
        ),
        migrations.AddField(
            model_name='positionapproval',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
