# Generated by Django 3.2.13 on 2022-05-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0043_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
