# Generated by Django 3.2.13 on 2022-05-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_activitylogs_type_id'),
        ('form', '0044_reminder_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='sender_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_sender', to='user.profile'),
        ),
    ]
