# Generated by Django 3.2.13 on 2022-06-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_department'),
        ('form', '0045_reminder_sender_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBoardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Job board template for specific company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_board_template_company', to='company.company')),
            ],
        ),
    ]
