# Generated by Django 3.2.13 on 2022-06-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0046_jobboardtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescriptionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_file', models.FileField(blank=True, help_text='Select file', null=True, upload_to='media/')),
                ('image_file_name', models.CharField(blank=True, help_text='Enter the image file name', max_length=250, null=True)),
                ('image_field_name', models.CharField(blank=True, help_text='Enter image field name', max_length=250, null=True)),
                ('image_file_type', models.CharField(blank=True, help_text='Enter image file type', max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Select your prefrences')),
                ('is_deleted', models.BooleanField(default=False, help_text='Select your prefrences')),
                ('can_delete', models.BooleanField(default=True, help_text='Select your prefrences')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Select your prefrences')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated time')),
            ],
        ),
    ]
