# Generated by Django 3.2.13 on 2022-06-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0047_jobdescriptionimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedposition',
            name='application_status',
            field=models.CharField(choices=[('reject', 'reject'), ('active', 'active'), ('hold', 'hold')], default='draft', max_length=10),
        ),
    ]
