# Generated by Django 3.2.13 on 2022-07-01 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_department'),
        ('form', '0050_auto_20220701_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasontype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
