# Generated by Django 3.2.13 on 2022-07-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0051_reasontype_company'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='reason',
        #     name='reason',
        #     field=models.ForeignKey(help_text='Enter your Education', on_delete=django.db.models.deletion.CASCADE, related_name='reason_company', to='form.reasontype'),
        # ),
    ]
