# Generated by Django 3.2.13 on 2022-07-05 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0051_reasontype_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reason',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_type_company', to='form.reasontype'),
        ),
    ]
