# Generated by Django 3.2.13 on 2022-07-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0052_auto_20220705_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerapproval',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_approvals', to='form.formdata'),
        ),
        migrations.AlterField(
            model_name='positionapproval',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_approvals', to='form.formdata'),
        ),
    ]
