# Generated by Django 3.2.13 on 2022-07-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0052_alter_reason_reason'),
        ('form', '0053_auto_20220705_1214'),
    ]

    operations = [
    ]
