# Generated by Django 3.2.13 on 2022-07-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0054_merge_20220708_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
