# Generated by Django 3.2.13 on 2022-07-12 06:17

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0055_alter_reason_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedposition',
            name='applicant_details',
            field=models.JSONField(default=form.models.contact_default),
        ),
    ]
