# Generated by Django 3.2.13 on 2022-07-15 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0056_appliedposition_applicant_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedposition',
            name='joining_date',
            field=models.DateField(blank=True, help_text='joining_date', null=True),
        ),
        migrations.CreateModel(
            name='ApplicantDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doucument', models.FileField(blank=True, help_text='Select_file', null=True, upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date and time', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date and time', null=True)),
                ('applied_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_document', to='form.appliedposition')),
            ],
        ),
    ]
