# Generated by Django 3.2.13 on 2022-07-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0057_auto_20220715_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_block',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
