# Generated by Django 3.2.13 on 2022-07-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0058_field_field_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
    ]
