# Generated by Django 3.2.13 on 2022-10-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_user_encoded_id'),
        ('form', '0061_alter_appliedposition_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('guarantee_bonus', models.IntegerField(default=0)),
                ('sign_on_bonus', models.IntegerField(default=0)),
                ('relocation_bonus', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('target_compensation', models.IntegerField()),
                ('visa_required', models.BooleanField(default=False)),
                ('allowance', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('offered_by_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_by_profile', to='user.profile')),
                ('offered_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_to', to='form.appliedposition')),
            ],
        ),
    ]
