# Generated by Django 3.2.13 on 2022-10-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0063_alter_appliedposition_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedposition',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
