# Generated by Django 3.2.13 on 2022-10-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0064_appliedposition_withdrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
