# Generated by Django 3.2.13 on 2022-10-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0065_alter_offerletter_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='visa_required',
            field=models.CharField(default='Visa is not required.', max_length=250),
        ),
    ]
