# Generated by Django 3.2.13 on 2022-10-31 12:48

from django.db import migrations, models
import tkinter.tix


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0066_alter_offerletter_visa_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='visa_required',
            field=models.CharField(blank=tkinter.tix.Tree, default='Visa is not required.', max_length=250, null=True),
        ),
    ]
