# Generated by Django 3.2.13 on 2022-11-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0067_alter_offerletter_visa_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='guarantee_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='relocation_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='sign_on_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
