# Generated by Django 3.2.13 on 2022-11-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0017_alter_university_country'),
        ('form', '0068_auto_20221101_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='offer-letters/'),
        ),
        migrations.CreateModel(
            name='OfferLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(max_length=250)),
                ('offer_id', models.CharField(max_length=12)),
                ('attached_letter', models.FileField(upload_to='offer_letter_templates')),
                ('status', models.BooleanField(default=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter_country', to='primary_data.country')),
            ],
        ),
    ]
