# Generated by Django 3.2.13 on 2022-11-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0069_auto_20221102_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='currency',
            field=models.CharField(default='INR', max_length=12),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='offer_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template', to='form.offerlettertemplate'),
        ),
    ]
