# Generated by Django 3.2.13 on 2022-11-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0070_auto_20221102_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerletter',
            name='file',
        ),
        migrations.RemoveField(
            model_name='offerletter',
            name='offer_template',
        ),
    ]
