# Generated by Django 3.2.13 on 2022-11-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0072_auto_20221107_0757"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='offerletter',
        #     name='signed_file',
        #     field=models.FileField(blank=True, default=None, null=True, upload_to='offer-letters/'),
        # ),
    ]
