# Generated by Django 3.2.13 on 2022-11-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0072_auto_20221107_0757'),
        ('form', '0072_offerletter_signed_file'),
    ]

    operations = [
    ]
