# Generated by Django 3.2.13 on 2022-11-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0073_offerletter_signed_file'),
        ('form', '0074_auto_20221107_0938'),
    ]

    operations = [
    ]
