# Generated by Django 3.2.13 on 2022-11-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0076_auto_20221107_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated time')),
            ],
        ),
    ]
