# Generated by Django 3.2.13 on 2022-11-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0077_careertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='withdraw',
            field=models.BooleanField(default=False),
        ),
    ]
