# Generated by Django 3.2.13 on 2022-11-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0078_offerletter_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('hold', 'hold'), ('closed', 'closed')], default='draft', max_length=10),
        ),
    ]
