# Generated by Django 3.2.13 on 2022-11-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0079_alter_formdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='reporting_manager',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
