# Generated by Django 3.2.16 on 2022-11-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0081_auto_20221121_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedposition',
            name='rejection_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
