# Generated by Django 3.2.16 on 2022-11-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0082_appliedposition_rejection_mail_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedposition',
            name='rejection_mail_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
