# Generated by Django 3.2.16 on 2022-11-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0083_alter_appliedposition_rejection_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='decline_reason',
            field=models.CharField(default='No Reason', max_length=250),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='is_decline',
            field=models.BooleanField(default=False),
        ),
    ]
