# Generated by Django 3.2.16 on 2022-12-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0084_auto_20221128_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedposition',
            name='refereed_by_profile',
        ),
    ]
