# Generated by Django 3.2.16 on 2022-12-12 05:07

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0085_remove_appliedposition_refereed_by_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedposition',
            name='refereed_by_profile',
            field=models.JSONField(blank=True, default=form.models.get_ref_default, null=True),
        ),
    ]
