# Generated by Django 3.2.16 on 2022-12-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0086_appliedposition_refereed_by_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='job_description',
            field=models.FileField(blank=True, default=None, help_text='Select file', null=True, upload_to='media/jd'),
        ),
    ]
