# Generated by Django 3.2.16 on 2022-12-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_company_url'),
        ('form', '0087_formdata_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='careertemplate',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='career_template', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careertemplate',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
