# Generated by Django 3.2.16 on 2022-12-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0088_auto_20221216_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careertemplate',
            old_name='internal',
            new_name='is_internal',
        ),
        migrations.AddField(
            model_name='careertemplate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
