# Generated by Django 3.2.16 on 2023-01-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0093_answer_customquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.formdata'),
        ),
    ]
