# Generated by Django 3.2.16 on 2023-01-18 07:39

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0094_answer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='careertemplate',
            name='design',
            field=models.JSONField(default=form.models.get_json_default),
        ),
    ]
