# Generated by Django 3.2.16 on 2023-01-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0095_careertemplate_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='start_date_change',
            field=models.BooleanField(default=False),
        ),
    ]
