# Generated by Django 3.2.16 on 2023-02-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0096_offerletter_start_date_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='docusign_envelope_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
