# Generated by Django 3.2.16 on 2023-02-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0097_offerletter_docusign_envelope_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customquestion',
            name='position',
        ),
        migrations.AddField(
            model_name='customquestion',
            name='position',
            field=models.ManyToManyField(blank=True, null=True, to='form.FormData'),
        ),
    ]
