# Generated by Django 3.2.16 on 2023-03-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0099_auto_20230301_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerlettertemplate',
            name='employment_type',
        ),
    ]
