# Generated by Django 3.2.16 on 2023-03-01 12:20

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0100_remove_offerlettertemplate_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettertemplate',
            name='employment_type',
            field=models.JSONField(default=form.models.get_json_default),
        ),
    ]
