# Generated by Django 3.2.16 on 2023-03-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0101_offerlettertemplate_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='allowance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='basic_salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
