# Generated by Django 3.2.16 on 2023-03-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0102_auto_20230306_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='allowance',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='basic_salary',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='bonus',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='guarantee_bonus',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='relocation_bonus',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='sign_on_bonus',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='target_compensation',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
