# Generated by Django 3.2.16 on 2023-03-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0103_auto_20230306_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionapproval',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
