# Generated by Django 3.2.16 on 2023-03-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0104_positionapproval_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerapproval',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
