# Generated by Django 3.2.16 on 2023-03-24 08:50

from django.db import migrations, models
import django.db.models.deletion
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_auto_20230322_0936'),
        ('form', '0105_offerapproval_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnapprovedAppliedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('refereed_by_profile', models.JSONField(blank=True, default=form.models.get_ref_default, null=True)),
                ('data', models.JSONField(default=form.models.contact_default)),
                ('applicant_details', models.JSONField(default=form.models.contact_default)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Choose job location for specific company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unapproved_applied_position_company', to='company.company')),
                ('form_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formdata')),
            ],
        ),
    ]
