# Generated by Django 3.2.16 on 2023-03-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0106_unapprovedappliedposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
