# Generated by Django 3.2.16 on 2023-04-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0107_offerletter_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionapproval',
            name='approval_type',
            field=models.CharField(blank=True, choices=[('All at once', 'a-a-o'), ('one to one', 'o-t-o')], default='one to one', max_length=11, null=True),
        ),
    ]
