# Generated by Django 3.2.16 on 2023-04-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0108_alter_positionapproval_approval_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerapproval',
            name='approval_type',
            field=models.CharField(blank=True, choices=[('All at once', 'a-a-o'), ('one to one', 'o-t-o')], default='one to one', max_length=11, null=True),
        ),
    ]
