# Generated by Django 3.2.16 on 2023-04-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_auto_20230321_0456'),
        ('form', '0110_formdata_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerapproval',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_to_profile', to='user.profile'),
        ),
    ]
