# Generated by Django 3.2.16 on 2023-05-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0111_offerapproval_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedposition',
            name='rejection_mail_sent',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
