# Generated by Django 3.2.16 on 2023-05-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0112_alter_appliedposition_rejection_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='offer_created_mail',
            field=models.BooleanField(default=False),
        ),
    ]
