# Generated by Django 3.2.16 on 2023-06-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0113_offerletter_offer_created_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
