# Generated by Django 3.2.16 on 2023-06-05 06:51

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0115_auto_20230605_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['field_name', 'company']),
        ),
    ]
