# Generated by Django 3.2.16 on 2023-06-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0116_alter_field_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='form_data_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='offer_letter_id',
            field=models.IntegerField(default=0),
        ),
    ]
