# Generated by Django 3.2.16 on 2023-06-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0118_rename_form_data_id_formdata_show_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerletter',
            old_name='offer_letter_id',
            new_name='show_offer_id',
        ),
    ]
