# Generated by Django 3.2.16 on 2023-07-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0119_rename_offer_letter_id_offerletter_show_offer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='has_joined',
            field=models.BooleanField(default=False),
        ),
    ]
