# Generated by Django 3.2.9 on 2022-05-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affinda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Select file', null=True, upload_to='affinda_files/')),
                ('file_name', models.CharField(blank=True, help_text='Enter the file name', max_length=250, null=True)),
                ('field_name', models.CharField(blank=True, help_text='Enter field name', max_length=250, null=True)),
                ('file_type', models.CharField(blank=True, help_text='Enter file type', max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Select your prefrences')),
                ('is_deleted', models.BooleanField(default=False, help_text='Select your prefrences')),
                ('can_delete', models.BooleanField(default=True, help_text='Select your prefrences')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Select your prefrences')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated time')),
            ],
        ),
    ]
