# Generated by Django 3.2.13 on 2022-05-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affinda',
            name='file',
            field=models.FileField(blank=True, help_text='Select file', null=True, upload_to='media/'),
        ),
    ]
