# Generated by Django 3.2.13 on 2022-10-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0005_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(help_text='identity for organization model', primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, help_text='Enter Company Name', max_length=250, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_email', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_employees', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('first_employee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_employee_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('second_employee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('second_employee_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date and time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date and time')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
