# Generated by Django 3.2.13 on 2022-10-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_user_encoded_id'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='first_employee_contact',
            new_name='contact_person_one',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='first_employee_name',
            new_name='contact_person_two',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organization_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_employees',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='second_employee_contact',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='second_employee_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='org_employee_id',
            field=models.ForeignKey(default=1, help_text='Enter your Employee id', on_delete=django.db.models.deletion.CASCADE, related_name='organization_employee_id', to='user.profile'),
            preserve_default=False,
        ),
    ]
