# Generated by Django 3.2.13 on 2022-10-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='organization',
        #     name='organization_email',
        #     field=models.CharField(blank=True, max_length=150, null=True),
        # ),
    ]
