# Generated by Django 3.2.13 on 2022-10-11 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_auto_20221010_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_employee_id',
            field=models.ForeignKey(help_text='Enter your Employee id', on_delete=django.db.models.deletion.CASCADE, related_name='organization_employee_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
