# Generated by Django 3.2.13 on 2022-10-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_organization_email'),
        ('organization', '0003_alter_organization_org_employee_id'),
    ]

    operations = [
    ]
