# Generated by Django 3.2.13 on 2022-10-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_merge_20221013_1128'),
    ]

    operations = [
       # migrations.RemoveField(
       #     model_name='organization',
       #     name='organization_email',
       # ),
    ]
