# Generated by Django 3.2.13 on 2022-10-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_organization_organization_email'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='organization',
        #     name='organization_email',
        # ),
    ]
