# Generated by Django 3.2.13 on 2022-11-07 03:35

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_organization_organization_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='company',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_person_one',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_person_two',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='org_employee_id',
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_1',
            field=models.JSONField(default=organization.models.get_default_list),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='fax',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='office',
            field=models.JSONField(default=organization.models.get_default_dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='office_id_1',
            field=models.JSONField(default=organization.models.get_default_list),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_no',
            field=models.CharField(blank=True, default=None, help_text='Enter your contact number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_contact_1',
            field=models.CharField(blank=True, default=None, help_text='Enter your contact number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='secondary_contact_2',
            field=models.CharField(blank=True, default=None, help_text='Enter your contact number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, default='test', max_length=50, null=True),
        ),
    ]
