# Generated by Django 3.2.13 on 2022-11-07 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_department'),
        ('organization', '0007_auto_20221107_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
