# Generated by Django 3.2.13 on 2022-11-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20221107_1039'),
        ('organization', '0008_organization_company'),
    ]

    operations = [
    ]
