# Generated by Django 3.2.13 on 2022-11-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_merge_20221107_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='primary_contact_1',
            field=models.CharField(blank=True, default=None, help_text='Enter primary contact name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='secondary_contact_2',
            field=models.CharField(blank=True, default=None, help_text='Enter secondary contact name', max_length=50, null=True),
        ),
    ]
