# Generated by Django 3.2.16 on 2023-03-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20230222_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='region',
        ),
    ]
