# Generated by Django 3.2.16 on 2023-03-02 07:07

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20230302_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.JSONField(default=organization.models.get_default_dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.JSONField(default=organization.models.get_default_dict),
        ),
    ]
