# Generated by Django 3.2.16 on 2023-03-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20230302_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
    ]
