# Generated by Django 3.2.16 on 2023-03-03 06:48

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_remove_organization_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.JSONField(default=organization.models.get_default_list),
        ),
    ]
