# Generated by Django 3.2.16 on 2023-03-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_organization_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='total_hired',
        ),
    ]
