# Generated by Django 3.2.16 on 2023-03-20 04:54

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_remove_organization_total_hired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address_1',
            field=models.JSONField(default=organization.models.get_default_list_addr),
        ),
        migrations.AlterField(
            model_name='organization',
            name='office_id_1',
            field=models.JSONField(default=organization.models.get_default_list_off),
        ),
    ]
