# Generated by Django 3.2.9 on 2022-04-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_site', models.CharField(blank=True, help_text='Enter Job Site', max_length=250, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Enter your start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Enter your end date', null=True)),
                ('last_invoice', models.DateField(blank=True, help_text='Enter last invoice', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date and time', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date and time', null=True)),
            ],
        ),
    ]
