# Generated by Django 3.2.9 on 2022-04-25 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsites',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='jobsites',
            name='last_invoice',
        ),
        migrations.RemoveField(
            model_name='jobsites',
            name='start_date',
        ),
        migrations.AddField(
            model_name='jobsites',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your preferences'),
        ),
        migrations.AddField(
            model_name='jobsites',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your preferences'),
        ),
        migrations.AlterField(
            model_name='jobsites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='created date and time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobsites',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='updated date and time'),
            preserve_default=False,
        ),
    ]
