# Generated by Django 3.2.16 on 2023-03-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0003_jobsites_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsites',
            name='job_ads_inventory',
            field=models.CharField(blank=True, help_text='Enter Job Ads Inventory', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jobsites',
            name='package_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jobsites',
            name='package_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jobsites',
            name='resume_search_inventory',
            field=models.CharField(blank=True, help_text='Enter Search Inventory', max_length=250, null=True),
        ),
    ]
