# Generated by Django 3.2.16 on 2023-03-13 13:17

from django.db import migrations, models
import jobsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0004_auto_20230313_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsites',
            name='country',
            field=models.JSONField(default=jobsite.models.get_json_default),
        ),
    ]
