# Generated by Django 3.2.9 on 2022-01-13 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220113_0515'),
        ('stage', '0002_alter_stage_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpipeline',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your Country name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='historicalpipeline',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='created datetime'),
        ),
        migrations.AlterField(
            model_name='historicalpipeline',
            name='description',
            field=models.TextField(blank=True, help_text='Add description', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpipeline',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='historicalpipeline',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='historicalpipeline',
            name='pipeline_name',
            field=models.CharField(help_text='Enter name of your pipeline', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalpipeline',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Sort by'),
        ),
        migrations.AlterField(
            model_name='historicalpipeline',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated datetime'),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your Country name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='created date time'),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='description',
            field=models.TextField(blank=True, help_text='Add description', null=True),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='pipeline',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose type of pipeline', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stage.pipeline'),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Sort by'),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='stage_name',
            field=models.CharField(help_text='Enter stage name', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated date and time'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='company',
            field=models.ForeignKey(help_text='Choose your Country name', on_delete=django.db.models.deletion.CASCADE, related_name='company_pipeline', to='company.company'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='created datetime'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='description',
            field=models.TextField(blank=True, help_text='Add description', null=True),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_name',
            field=models.CharField(help_text='Enter name of your pipeline', max_length=150),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Sort by'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated datetime'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='company',
            field=models.ForeignKey(help_text='Choose your Country name', on_delete=django.db.models.deletion.CASCADE, related_name='stage_pipeline', to='company.company'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='created date time'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True, help_text='Add description', null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='pipeline',
            field=models.ForeignKey(blank=True, help_text='Choose type of pipeline', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_pipeline', to='stage.pipeline'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Sort by'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_name',
            field=models.CharField(help_text='Enter stage name', max_length=150),
        ),
        migrations.AlterField(
            model_name='stage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time'),
        ),
    ]
