# Generated by Django 3.2.9 on 2022-01-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0003_auto_20220113_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpipeline',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your preferences'),
        ),
        migrations.AlterField(
            model_name='historicalpipeline',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your preferences'),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your preferences'),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your preferences'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your preferences'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your preferences'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your preferences'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your preferences'),
        ),
    ]
