# Generated by Django 3.2.9 on 2022-01-20 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20220113_0515'),
        ('scorecard', '0006_auto_20220120_1047'),
        ('company', '0003_auto_20220113_0515'),
        ('form', '0011_auto_20220120_1047'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stage', '0004_auto_20220120_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1, help_text='Sort by')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['position', 'company', 'stage'])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date and time')),
                ('attribute', models.ManyToManyField(blank=True, null=True, related_name='positing_stage_attribute', to='scorecard.Attribute')),
                ('company', models.ForeignKey(help_text='Choose your Country name', on_delete=django.db.models.deletion.CASCADE, related_name='stage_pipeline_company', to='company.company')),
                ('interviewer', models.ManyToManyField(blank=True, null=True, related_name='positing_stage_interviewer', to='user.Profile')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formdata')),
                ('stage', models.ForeignKey(help_text='stage for specific job', on_delete=django.db.models.deletion.CASCADE, related_name='job_stage_pipeline', to='stage.stage')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPositionStage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1, help_text='Sort by')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['position', 'company', 'stage'])),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='created date time')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='updated date and time')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your Country name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='form.formdata')),
                ('stage', models.ForeignKey(blank=True, db_constraint=False, help_text='stage for specific job', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stage.stage')),
            ],
            options={
                'verbose_name': 'historical position stage',
                'db_table': 'job_stage_pipeline_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
