# Generated by Django 3.2.9 on 2022-02-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20220113_0515'),
        ('scorecard', '0006_auto_20220120_1047'),
        ('stage', '0005_historicalpositionstage_positionstage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionstage',
            name='interviewer',
        ),
        migrations.AddField(
            model_name='positionstage',
            name='profiles',
            field=models.ManyToManyField(blank=True, help_text='user profile list who are going to interviewing this position stage', related_name='positing_stage_profiles', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='positionstage',
            name='attribute',
            field=models.ManyToManyField(blank=True, help_text='attributes list to that specific position', related_name='positing_stage_attribute', to='scorecard.Attribute'),
        ),
    ]
