# Generated by Django 3.2.9 on 2022-03-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0006_auto_20220202_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpositionstage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalpositionstage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpositionstage',
            name='position',
        ),
        migrations.RemoveField(
            model_name='historicalpositionstage',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='historicalstage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalstage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstage',
            name='pipeline',
        ),
        migrations.DeleteModel(
            name='HistoricalPipeline',
        ),
        migrations.DeleteModel(
            name='HistoricalPositionStage',
        ),
        migrations.DeleteModel(
            name='HistoricalStage',
        ),
    ]
