# Generated by Django 3.2.9 on 2022-03-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0007_auto_20220315_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='is_mandatory',
            field=models.BooleanField(default=True, help_text='Select your preferences'),
        ),
    ]
