# Generated by Django 3.2.9 on 2022-03-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0008_stage_is_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Select your preferences'),
        ),
    ]
