# Generated by Django 3.2.13 on 2022-05-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0009_auto_20220509_0358'),
        ('stage', '0009_alter_stage_is_mandatory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionstage',
            name='attribute',
        ),
        migrations.AddField(
            model_name='positionstage',
            name='competency',
            field=models.ManyToManyField(blank=True, help_text='attributes list to that specific position', related_name='positing_stage_attribute', to='scorecard.PositionCompetencyAndAttribute'),
        ),
    ]
