# Generated by Django 3.2.13 on 2022-05-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0010_auto_20220509_0437'),
        ('stage', '0010_auto_20220509_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionstage',
            name='competency',
            field=models.ManyToManyField(blank=True, help_text='attributes list to that specific position', related_name='positing_stage_competency', to='scorecard.PositionCompetencyAndAttribute'),
        ),
    ]
