# Generated by Django 3.2.16 on 2023-04-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0011_alter_positionstage_competency'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='is_interview',
            field=models.BooleanField(default=False),
        ),
    ]
