# Generated by Django 3.2.16 on 2022-12-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='additional_info',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='notifications',
            name='redirect_slug',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
