# Generated by Django 3.2.16 on 2022-12-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20221201_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='notifications',
            name='additional_info',
            field=models.JSONField(default={}),
        ),
    ]
