# Generated by Django 3.2.16 on 2022-12-12 05:05

from django.db import migrations, models
import notification.models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20221202_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='additional_info',
            field=models.JSONField(default=notification.models.json_default),
        ),
    ]
