# Generated by Django 3.2.16 on 2023-05-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notifications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='event_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
