# Generated by Django 3.2.9 on 2021-12-03 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0004_auto_20211201_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='historicaleducation',
            name='locations',
        ),
        migrations.AddField(
            model_name='education',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primary_data.country'),
        ),
    ]
