# Generated by Django 3.2.9 on 2021-12-03 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0005_auto_20211203_1026'),
        ('user', '0002_auto_20211203_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AddField(
            model_name='historicaleducation',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.country'),
        ),
        migrations.AddField(
            model_name='historicaleducation',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile'),
        ),
    ]
