# Generated by Django 3.2.9 on 2021-12-05 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_profile_skill"),
        ("primary_data", "0006_auto_20211203_1026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="user.profile",
            ),
            preserve_default=False,
        ),
    ]
