# Generated by Django 3.2.9 on 2021-12-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0007_alter_education_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university', to='primary_data.university'),
        ),
    ]
