# Generated by Django 3.2.9 on 2021-12-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0009_experience_historicalexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_type',
            field=models.CharField(blank=True, choices=[('10', '10th'), ('12', '12th'), ('GD', 'Graduation/Diploma'), ('MP', 'Masters/Post-Graduation'), ('DP', 'Doctorate/PhD')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicaleducation',
            name='education_type',
            field=models.CharField(blank=True, choices=[('10', '10th'), ('12', '12th'), ('GD', 'Graduation/Diploma'), ('MP', 'Masters/Post-Graduation'), ('DP', 'Doctorate/PhD')], max_length=2, null=True),
        ),
    ]
