# Generated by Django 3.2.9 on 2021-12-31 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0011_auto_20211224_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primary_data.country'),
        ),
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalexperience',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.country'),
        ),
        migrations.AddField(
            model_name='historicalexperience',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
