# Generated by Django 3.2.9 on 2022-01-13 05:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20220110_0452'),
        ('primary_data', '0013_auto_20220103_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_one',
            field=models.CharField(blank=True, help_text='Enter Address 1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_three',
            field=models.CharField(blank=True, help_text='Enter Address 3', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_two',
            field=models.CharField(blank=True, help_text='Enter Address 2', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Choose your city', null=True, on_delete=django.db.models.deletion.CASCADE, to='primary_data.city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Choose your Country', null=True, on_delete=django.db.models.deletion.CASCADE, to='primary_data.country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, help_text='Enter your pincode', null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Choose your State', null=True, on_delete=django.db.models.deletion.CASCADE, to='primary_data.state'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(help_text='Choose your Country', on_delete=django.db.models.deletion.RESTRICT, to='primary_data.country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, help_text='Add description'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Enter name of your city', max_length=200),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(help_text='Choose your State', on_delete=django.db.models.deletion.RESTRICT, to='primary_data.state'),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, help_text='Enter Name of the Capital', max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='created date and time in Country model', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, help_text='Currency type', max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, help_text='Add description'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(blank=True, help_text='Enter ISO2', max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(blank=True, help_text='Enter ISO3', max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Name of the Country', max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, help_text='Enter your 10 digit number', max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Choose your Country', null=True, on_delete=django.db.models.deletion.CASCADE, to='primary_data.country'),
        ),
        migrations.AlterField(
            model_name='education',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_type',
            field=models.ForeignKey(help_text='Choose your Education type', on_delete=django.db.models.deletion.CASCADE, to='primary_data.educationtype'),
        ),
        migrations.AlterField(
            model_name='education',
            name='passing_out_year',
            field=models.IntegerField(choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, help_text='Choose your passing out year'),
        ),
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(help_text='Enter your profile details', on_delete=django.db.models.deletion.CASCADE, related_name='education', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Select your university', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university', to='primary_data.university'),
        ),
        migrations.AlterField(
            model_name='education',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='name',
            field=models.CharField(help_text='Enter type of your Education', max_length=150),
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(help_text='Enter your Company name', max_length=250),
        ),
        migrations.AlterField(
            model_name='experience',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Choose your Country', null=True, on_delete=django.db.models.deletion.CASCADE, to='primary_data.country'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_current_company',
            field=models.BooleanField(default=False, help_text='Tick mark your prefrence'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='join_date',
            field=models.DateField(blank=True, help_text='Joining Date', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='leave_date',
            field=models.DateField(blank=True, help_text='Leaving date', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(help_text='Enter your profile', on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role_and_responsibilities',
            field=models.TextField(blank=True, help_text='Describe your roles and responsibility'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='skill',
            field=models.ManyToManyField(blank=True, help_text='Choose your skills and ', to='primary_data.KeySkill'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(blank=True, help_text='Enter job tittle', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='address_one',
            field=models.CharField(blank=True, help_text='Enter Address 1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='address_three',
            field=models.CharField(blank=True, help_text='Enter Address 3', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='address_two',
            field=models.CharField(blank=True, help_text='Enter Address 2', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='city',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your city', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.city'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your Country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.country'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, help_text='Enter your pincode', null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='state',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your State', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.state'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcity',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your Country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.country'),
        ),
        migrations.AlterField(
            model_name='historicalcity',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcity',
            name='description',
            field=models.TextField(blank=True, help_text='Add description'),
        ),
        migrations.AlterField(
            model_name='historicalcity',
            name='name',
            field=models.CharField(help_text='Enter name of your city', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalcity',
            name='state',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your State', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.state'),
        ),
        migrations.AlterField(
            model_name='historicalcity',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcountry',
            name='capital',
            field=models.CharField(blank=True, help_text='Enter Name of the Capital', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcountry',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='created date and time in Country model', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcountry',
            name='currency',
            field=models.CharField(blank=True, help_text='Currency type', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcountry',
            name='description',
            field=models.TextField(blank=True, help_text='Add description'),
        ),
        migrations.AlterField(
            model_name='historicalcountry',
            name='iso2',
            field=models.CharField(blank=True, help_text='Enter ISO2', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcountry',
            name='iso3',
            field=models.CharField(blank=True, help_text='Enter ISO3', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcountry',
            name='name',
            field=models.CharField(help_text='Name of the Country', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalcountry',
            name='phone_code',
            field=models.CharField(blank=True, help_text='Enter your 10 digit number', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcountry',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your Country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.country'),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='education_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your Education type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.educationtype'),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='passing_out_year',
            field=models.IntegerField(choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, help_text='Choose your passing out year'),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Enter your profile details', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='university',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Select your university', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.university'),
        ),
        migrations.AlterField(
            model_name='historicaleducation',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicaleducationtype',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicaleducationtype',
            name='name',
            field=models.CharField(help_text='Enter type of your Education', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicaleducationtype',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicalexperience',
            name='company_name',
            field=models.CharField(help_text='Enter your Company name', max_length=250),
        ),
        migrations.AlterField(
            model_name='historicalexperience',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your Country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.country'),
        ),
        migrations.AlterField(
            model_name='historicalexperience',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicalexperience',
            name='is_current_company',
            field=models.BooleanField(default=False, help_text='Tick mark your prefrence'),
        ),
        migrations.AlterField(
            model_name='historicalexperience',
            name='join_date',
            field=models.DateField(blank=True, help_text='Joining Date', null=True),
        ),
        migrations.AlterField(
            model_name='historicalexperience',
            name='leave_date',
            field=models.DateField(blank=True, help_text='Leaving date', null=True),
        ),
        migrations.AlterField(
            model_name='historicalexperience',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Enter your profile', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='historicalexperience',
            name='role_and_responsibilities',
            field=models.TextField(blank=True, help_text='Describe your roles and responsibility'),
        ),
        migrations.AlterField(
            model_name='historicalexperience',
            name='title',
            field=models.CharField(blank=True, help_text='Enter job tittle', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalexperience',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeyskill',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeyskill',
            name='skill',
            field=models.CharField(db_index=True, help_text='Enter your Skills', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalkeyskill',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicalkeyskill',
            name='verified',
            field=models.BooleanField(default=False, help_text='Tick the box'),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your Country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.country'),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='description',
            field=models.TextField(blank=True, help_text='Add description'),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='name',
            field=models.CharField(help_text='Enter your State', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicaluniversity',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your Country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='primary_data.country'),
        ),
        migrations.AlterField(
            model_name='historicaluniversity',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='created date and time ', null=True),
        ),
        migrations.AlterField(
            model_name='historicaluniversity',
            name='description',
            field=models.TextField(blank=True, help_text='Add description'),
        ),
        migrations.AlterField(
            model_name='historicaluniversity',
            name='domain',
            field=models.CharField(blank=True, help_text='Enter Domain Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaluniversity',
            name='name',
            field=models.CharField(help_text='Enter name of your university', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaluniversity',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='historicaluniversity',
            name='web_page',
            field=models.CharField(blank=True, help_text='Enter webpage details', max_length=200),
        ),
        migrations.AlterField(
            model_name='keyskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='keyskill',
            name='skill',
            field=models.CharField(help_text='Enter your Skills', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='keyskill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='keyskill',
            name='verified',
            field=models.BooleanField(default=False, help_text='Tick the box'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(help_text='Choose your Country', on_delete=django.db.models.deletion.RESTRICT, to='primary_data.country'),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='created date and time', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.TextField(blank=True, help_text='Add description'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(help_text='Enter your State', max_length=200),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.ForeignKey(help_text='Choose your Country', on_delete=django.db.models.deletion.RESTRICT, to='primary_data.country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='created date and time ', null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, help_text='Add description'),
        ),
        migrations.AlterField(
            model_name='university',
            name='domain',
            field=models.CharField(blank=True, help_text='Enter Domain Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(help_text='Enter name of your university', max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time', null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='web_page',
            field=models.CharField(blank=True, help_text='Enter webpage details', max_length=200),
        ),
    ]
