# Generated by Django 3.2.9 on 2022-03-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0014_auto_20220113_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcity',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicalcity',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcity',
            name='state',
        ),
        migrations.RemoveField(
            model_name='historicalcountry',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaleducation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicaleducation',
            name='education_type',
        ),
        migrations.RemoveField(
            model_name='historicaleducation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaleducation',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='historicaleducation',
            name='university',
        ),
        migrations.RemoveField(
            model_name='historicaleducationtype',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalexperience',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicalexperience',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalexperience',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='historicalkeyskill',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstate',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicalstate',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluniversity',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicaluniversity',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalAddress',
        ),
        migrations.DeleteModel(
            name='HistoricalCity',
        ),
        migrations.DeleteModel(
            name='HistoricalCountry',
        ),
        migrations.DeleteModel(
            name='HistoricalEducation',
        ),
        migrations.DeleteModel(
            name='HistoricalEducationType',
        ),
        migrations.DeleteModel(
            name='HistoricalExperience',
        ),
        migrations.DeleteModel(
            name='HistoricalKeySkill',
        ),
        migrations.DeleteModel(
            name='HistoricalState',
        ),
        migrations.DeleteModel(
            name='HistoricalUniversity',
        ),
    ]
