# Generated by Django 3.2.9 on 2022-03-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0015_auto_20220315_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_image',
            field=models.FileField(blank=True, help_text='Select country representative image', null=True, upload_to='media/'),
        ),
    ]
