# Generated by Django 3.2.13 on 2022-10-17 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0016_country_country_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Choose your Country', null=True, on_delete=django.db.models.deletion.RESTRICT, to='primary_data.country'),
        ),
    ]
