# Generated by Django 3.2.16 on 2023-01-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0019_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(help_text='Enter industry name', max_length=150, unique=True),
        ),
    ]
