# Generated by Django 3.2.9 on 2022-02-15 07:22

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_auto_20220113_0515'),
        ('primary_data', '0014_auto_20220113_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Referral_Name', models.CharField(blank=True, help_text='Enter Referral Name', max_length=20, null=True, unique=True)),
                ('Level', models.CharField(max_length=40)),
                ('Job_Code', models.CharField(help_text='Enter job code', max_length=20)),
                ('position_tittle', models.CharField(max_length=30)),
                ('Currency', models.IntegerField()),
                ('Referral_Amount', models.IntegerField()),
                ('Country_Payout_Policy', models.CharField(max_length=1000)),
                ('Referral_Policy_Document', models.ImageField(upload_to='')),
                ('is_approve', models.BooleanField(default=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['Referral_Name', 'Currency', 'Country'])),
                ('is_active', models.BooleanField(default=True, help_text='user is active')),
                ('is_deleted', models.BooleanField(default=False, help_text='to delete the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(help_text='Company domain', on_delete=django.db.models.deletion.RESTRICT, to='company.company')),
                ('Country', models.ForeignKey(help_text='Choose your Country', on_delete=django.db.models.deletion.RESTRICT, to='primary_data.country')),
                ('Region', models.ForeignKey(help_text='Enter your Region', on_delete=django.db.models.deletion.RESTRICT, to='primary_data.state')),
            ],
        ),
    ]
