# Generated by Django 3.2.9 on 2022-02-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='Referral_Policy_Document',
        ),
    ]
