# Generated by Django 3.2.9 on 2022-02-17 05:26

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_remove_referral_referral_policy_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='Job_Code',
            new_name='job_code',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='Referral_Name',
            new_name='referral_name',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='Region',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='Country_Payout_Policy',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='Currency',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='Level',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='Referral_Amount',
        ),
        migrations.AddField(
            model_name='referral',
            name='country_payout_policy',
            field=models.CharField(default=1, help_text='Enter Referral Policy', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='currency',
            field=models.IntegerField(default=1, help_text='Choose Currency type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='level',
            field=models.CharField(default=1, help_text='choose your level', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_amount',
            field=models.IntegerField(default=1, help_text='Enter Referral Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='position_tittle',
            field=models.CharField(help_text='Enter Position tittle', max_length=30),
        ),
        migrations.AlterField(
            model_name='referral',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['referral_name', 'currency', 'country']),
        ),
    ]
