# Generated by Django 3.2.9 on 2022-02-17 08:19

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_auto_20220217_0526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='region',
            new_name='state',
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_rate_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_rate_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['referral_name', 'company', 'country']),
        ),
    ]
