# Generated by Django 3.2.9 on 2022-02-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_auto_20220217_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='attach_referral_policy_document',
            field=models.FileField(blank=True, help_text='Select file', null=True, upload_to='media/'),
        ),
    ]
