# Generated by Django 3.2.9 on 2022-02-24 05:15

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0005_referral_attach_referral_policy_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("currency_name", models.CharField(help_text="Enter the name of Currency", max_length=100, unique=True)),
                ("slug", django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=["currency_name"])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "currency",
            },
        ),
    ]
