# Generated by Django 3.2.9 on 2022-02-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='currency',
            field=models.ForeignKey(help_text='Choose Currency type', on_delete=django.db.models.deletion.RESTRICT, to='referral.currency'),
        ),
    ]
