# Generated by Django 3.2.16 on 2023-02-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0098_auto_20230224_0739'),
        ('referral', '0008_rename_referral_referralpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpolicy',
            name='job_categories',
            field=models.ManyToManyField(to='form.JobCategory'),
        ),
        migrations.AddField(
            model_name='referralpolicy',
            name='positions',
            field=models.ManyToManyField(to='form.FormData'),
        ),
    ]
