# Generated by Django 3.2.16 on 2023-03-28 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0020_alter_industry_name'),
        ('form', '0106_unapprovedappliedposition'),
        ('referral', '0009_auto_20230224_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralpolicy',
            name='attach_referral_policy_document',
            field=models.FileField(blank=True, default=None, help_text='Select file', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='referralpolicy',
            name='country',
            field=models.ForeignKey(blank=True, default=None, help_text='Choose your Country', null=True, on_delete=django.db.models.deletion.RESTRICT, to='primary_data.country'),
        ),
        migrations.AlterField(
            model_name='referralpolicy',
            name='country_payout_policy',
            field=models.CharField(blank=True, default=None, help_text='Enter Referral Policy', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='referralpolicy',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, help_text='Choose Currency type', null=True, on_delete=django.db.models.deletion.RESTRICT, to='referral.currency'),
        ),
        migrations.AlterField(
            model_name='referralpolicy',
            name='job_categories',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='form.JobCategory'),
        ),
        migrations.AlterField(
            model_name='referralpolicy',
            name='job_code',
            field=models.CharField(blank=True, default=None, help_text='Enter job code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='referralpolicy',
            name='level',
            field=models.CharField(blank=True, default=None, help_text='choose your level', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='referralpolicy',
            name='position_tittle',
            field=models.CharField(blank=True, default=None, help_text='Enter Position tittle', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='referralpolicy',
            name='positions',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='form.FormData'),
        ),
        migrations.AlterField(
            model_name='referralpolicy',
            name='referral_amount',
            field=models.IntegerField(blank=True, default=None, help_text='Enter Referral Amount', null=True),
        ),
        migrations.AlterField(
            model_name='referralpolicy',
            name='referral_rate_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='referralpolicy',
            name='referral_rate_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='referralpolicy',
            name='state',
            field=models.ForeignKey(blank=True, default=None, help_text='Enter your Region', null=True, on_delete=django.db.models.deletion.RESTRICT, to='primary_data.state'),
        ),
    ]
