# Generated by Django 3.2.9 on 2021-12-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('role', '0002_historicalrole_history_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_role', to='auth.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission', to='role.role')),
            ],
            options={
                'db_table': 'roles_permission',
            },
        ),
        migrations.AddIndex(
            model_name='rolepermissions',
            index=models.Index(fields=['id', 'permission'], name='roles_permi_id_4b1008_idx'),
        ),
    ]
