# Generated by Django 3.2.9 on 2021-12-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('role', '0003_auto_20211207_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
    ]
