# Generated by Django 3.2.9 on 2021-12-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_role_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolePermissions',
        ),
    ]
