# Generated by Django 3.2.9 on 2022-01-13 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0003_auto_20220113_0515'),
        ('role', '0006_auto_20211230_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrole',
            name='can_delete',
            field=models.BooleanField(default=True, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your company name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='created date and time'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='name',
            field=models.CharField(help_text='Enter your role here', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated date and time'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_delete',
            field=models.BooleanField(default=True, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='role',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Choose your company name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='created date and time'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Enter your role here', max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(help_text='Choose your permission field from above and ', to='auth.Permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time'),
        ),
    ]
