# Generated by Django 3.2.9 on 2022-02-02 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('role', '0007_auto_20220113_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True, help_text='Select your preferences')),
                ('is_deleted', models.BooleanField(default=False, help_text='Select your preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date and time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date and time')),
            ],
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='can_delete',
            field=models.BooleanField(default=True, help_text='Select your preferences'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your preferences'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your preferences'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_delete',
            field=models.BooleanField(default=True, help_text='Select your preferences'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your preferences'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your preferences'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('write', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_access', to='role.access')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_role', to='role.role')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAccess',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('action_name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True, help_text='Select your preferences')),
                ('is_deleted', models.BooleanField(default=False, help_text='Select your preferences')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='created date and time')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='updated date and time')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical access',
                'db_table': 'access_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
