# Generated by Django 3.2.9 on 2022-02-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0008_auto_20220202_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='access',
            field=models.ForeignKey(help_text='user action relevent to infertalent product', on_delete=django.db.models.deletion.CASCADE, related_name='permission_access', to='role.access'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='delete',
            field=models.BooleanField(default=False, help_text='role has permission to delete specific action'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='read',
            field=models.BooleanField(default=False, help_text='role has permission to read specific action'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(help_text='user role on infertalent product', on_delete=django.db.models.deletion.CASCADE, related_name='permission_role', to='role.role'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='update',
            field=models.BooleanField(default=False, help_text='role has permission to update specific action'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='write',
            field=models.BooleanField(default=False, help_text='role has permission to write specific action'),
        ),
    ]
