# Generated by Django 3.2.9 on 2022-02-02 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('role', '0009_auto_20220202_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='created date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time'),
        ),
        migrations.CreateModel(
            name='HistoricalPermission',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('read', models.BooleanField(default=False, help_text='role has permission to read specific action')),
                ('write', models.BooleanField(default=False, help_text='role has permission to write specific action')),
                ('update', models.BooleanField(default=False, help_text='role has permission to update specific action')),
                ('delete', models.BooleanField(default=False, help_text='role has permission to delete specific action')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='created date and time')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='updated date and time')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('access', models.ForeignKey(blank=True, db_constraint=False, help_text='user action relevent to infertalent product', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='role.access')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, db_constraint=False, help_text='user role on infertalent product', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='role.role')),
            ],
            options={
                'verbose_name': 'historical permission',
                'db_table': 'permission_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
