# Generated by Django 3.2.9 on 2022-02-03 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('role', '0011_auto_20220203_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, help_text='role has permission to read specific action')),
                ('write', models.BooleanField(default=False, help_text='role has permission to write specific action')),
                ('update', models.BooleanField(default=False, help_text='role has permission to update specific action')),
                ('delete', models.BooleanField(default=False, help_text='role has permission to delete specific action')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date and time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date and time')),
                ('access', models.ForeignKey(help_text='user action relevent to infertalent product', on_delete=django.db.models.deletion.CASCADE, related_name='permission_access', to='role.access')),
                ('role', models.ForeignKey(help_text='user role on infertalent product', on_delete=django.db.models.deletion.CASCADE, related_name='permission_role', to='role.role')),
            ],
        ),
        migrations.RenameModel(
            old_name='HistoricalUserPermission',
            new_name='HistoricalRolePermission',
        ),
        migrations.AlterModelOptions(
            name='historicalrolepermission',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical role permission'},
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
