# Generated by Django 3.2.9 on 2022-02-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0012_auto_20220203_0750'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalrolepermission',
            table='role_permission_history',
        ),
    ]
