# Generated by Django 3.2.9 on 2022-02-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('role', '0013_alter_historicalrolepermission_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, help_text='Choose your permission field from above and ', to='auth.Permission'),
        ),
    ]
