# Generated by Django 3.2.9 on 2022-02-24 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('role', '0014_alter_role_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date and time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date and time')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRoleList',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('role_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='created date and time')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='updated date and time')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical role list',
                'db_table': 'role_list_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
