# Generated by Django 3.2.9 on 2022-02-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0015_historicalrolelist_rolelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrolepermission',
            old_name='write',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='rolepermission',
            old_name='write',
            new_name='create',
        ),
    ]
