# Generated by Django 3.2.13 on 2022-10-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0018_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
