# Generated by Django 3.2.9 on 2021-12-01 09:24

import company.models
from django.db import migrations, models
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('url_domain', models.CharField(help_text='company subdomain for infertalent product', max_length=250, unique=True)),
                ('company_host', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['company_name'])),
                ('logo', models.FileField(blank=True, default=None, null=True, upload_to=company.models.upload_company_logo)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('url_domain', models.CharField(db_index=True, help_text='company subdomain for infertalent product', max_length=250)),
                ('company_host', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['company_name'])),
                ('logo', models.TextField(blank=True, default=None, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical company',
                'db_table': 'company_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
