# Generated by Django 3.2.9 on 2022-01-13 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_host',
            field=models.CharField(blank=True, help_text='Enter Host Name for infertalent product', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, help_text='Enter Company Name', max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_owner',
            field=models.ForeignKey(blank=True, help_text='Enter the Company owner ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='created date and time'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(help_text='identity for company model', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='   '),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Check this box to delete the user'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time'),
        ),
        migrations.AlterField(
            model_name='company',
            name='url_domain',
            field=models.CharField(help_text='Company Domain Name', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='company_host',
            field=models.CharField(blank=True, help_text='Enter Host Name for infertalent product', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, help_text='Enter Company Name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='company_owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Enter the Company owner ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='created date and time'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='id',
            field=models.IntegerField(blank=True, db_index=True, help_text='identity for company model'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='is_active',
            field=models.BooleanField(default=True, help_text='   '),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Check this box to delete the user'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated date and time'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='url_domain',
            field=models.CharField(db_index=True, help_text='Company Domain Name', max_length=250),
        ),
    ]
