# Generated by Django 3.2.9 on 2022-03-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220113_0515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCompany',
        ),
    ]
