# Generated by Django 3.2.9 on 2022-03-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_delete_historicalcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(help_text='identity for department model', primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, help_text='Enter Department Name', max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created date and time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated date and time')),
            ],
        ),
    ]
