# Generated by Django 3.2.13 on 2022-11-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_url',
            field=models.CharField(blank=True, default=None, help_text='Enter the website link of the company', max_length=250, null=True),
        ),
    ]
