# Generated by Django 3.2.16 on 2022-12-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_department_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(blank=True, help_text='Enter Department Name', max_length=250, null=True),
        ),
    ]
