# Generated by Django 3.2.16 on 2023-01-12 09:44

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_gprrdocsandpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='gprrdocsandpolicy',
            name='options',
            field=models.JSONField(default=company.models.get_default_options),
        ),
    ]
