# Generated by Django 3.2.16 on 2023-01-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_gprrdocsandpolicy_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gprrdocsandpolicy',
            old_name='options',
            new_name='option_type',
        ),
    ]
