# Generated by Django 3.2.16 on 2023-01-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_rename_options_gprrdocsandpolicy_option_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gprrdocsandpolicy',
            old_name='option_type',
            new_name='options',
        ),
    ]
