# Generated by Django 3.2.16 on 2023-01-12 12:13

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_rename_option_type_gprrdocsandpolicy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gprrdocsandpolicy',
            name='option_type',
            field=models.CharField(blank=True, default='options', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='gprrdocsandpolicy',
            name='options',
            field=models.JSONField(blank=True, default=company.models.get_default_options, null=True),
        ),
    ]
