# Generated by Django 3.2.16 on 2023-01-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20230112_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gprrdocsandpolicy',
            name='topic',
            field=models.TextField(),
        ),
    ]
