# Generated by Django 3.2.16 on 2023-01-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_gprrdocsandpolicy_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, default=None, help_text='Enter the industry of the company', max_length=250, null=True),
        ),
    ]
