# Generated by Django 3.2.16 on 2023-01-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_featuresenalbled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturesEnalbled',
            new_name='FeaturesEnabled',
        ),
    ]
