# Generated by Django 3.2.16 on 2023-02-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_rename_featuresenalbled_featuresenabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='no_of_emp',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
