# Generated by Django 3.2.16 on 2023-02-10 10:10

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_company_no_of_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderCreds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendly', models.JSONField(blank=True, default=company.models.get_default_options, null=True)),
                ('docusign', models.JSONField(blank=True, default=company.models.get_default_options, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
