# Generated by Django 3.2.16 on 2023-02-17 09:39

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_serviceprovidercreds'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovidercreds',
            name='zoom',
            field=models.JSONField(blank=True, default=company.models.get_default_options, null=True),
        ),
    ]
