# Generated by Django 3.2.16 on 2023-03-13 06:02

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_serviceprovidercreds_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovidercreds',
            name='from_email',
            field=models.JSONField(blank=True, default=company.models.get_default_options, null=True),
        ),
    ]
