# Generated by Django 3.2.16 on 2023-03-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_serviceprovidercreds_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='policy',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tnc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
