# Generated by Django 3.2.16 on 2023-03-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20230314_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresenabled',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='featuresenabled',
            name='feature',
            field=models.CharField(choices=[('google-meet', 'Google Meet'), ('pdftron', 'PDFTron'), ('calendly', 'Calendly'), ('interviewer', 'Interviewer')], default='---', max_length=255),
        ),
    ]
