# Generated by Django 3.2.16 on 2023-03-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20230315_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuresenabled',
            options={'verbose_name_plural': 'Features'},
        ),
    ]
