# Generated by Django 3.2.16 on 2023-03-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_alter_featuresenabled_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresenabled',
            name='feature',
            field=models.CharField(choices=[('google-meet', 'Google Meet'), ('pdftron', 'PDFTron'), ('calendly', 'Calendly'), ('recruiter', 'Recruiter')], default='---', max_length=255),
        ),
    ]
