# Generated by Django 3.2.16 on 2023-03-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_alter_featuresenabled_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, error_messages={'unique': 'Company with this name already exist in the system, please use another name.'}, help_text='Enter Company Name', max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='url_domain',
            field=models.CharField(error_messages={'unique': 'Company with this url domain already exist in the system, please use another url domain.'}, help_text='Company Domain Name', max_length=250, unique=True),
        ),
    ]
