# Generated by Django 3.2.16 on 2023-04-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_auto_20230322_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gprrdocsandpolicy',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
