# Generated by Django 3.2.16 on 2023-06-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_alter_gprrdocsandpolicy_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='form_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='offer_id',
            field=models.IntegerField(default=0),
        ),
    ]
