# Generated by Django 3.2.9 on 2022-02-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='Enter the template name', max_length=30, unique=True)),
                ('template_type', models.CharField(help_text='choose template type', max_length=30)),
                ('description', models.CharField(help_text='add description', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='user is active')),
                ('is_deleted', models.BooleanField(default=False, help_text='to delete the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
