# Generated by Django 3.2.9 on 2022-03-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_template', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailTemplates',
            new_name='EmailTemplate',
        ),
    ]
