# Generated by Django 3.2.9 on 2022-04-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_template', '0002_rename_emailtemplates_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='description',
            field=models.CharField(blank=True, help_text='add description', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_name',
            field=models.CharField(blank=True, help_text='Enter the template name', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(blank=True, help_text='choose template type', max_length=30, null=True),
        ),
    ]
