# Generated by Django 3.2.9 on 2022-04-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_template', '0003_auto_20220415_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='add description', null=True),
        ),
    ]
