# Generated by Django 3.2.13 on 2022-10-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_template', '0005_emailtemplate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.TextField(blank=True, help_text='Subject', null=True),
        ),
    ]
