# Generated by Django 3.2.13 on 2022-10-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_department'),
        ('email_template', '0006_emailtemplate_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type_name', models.CharField(blank=True, help_text='Enter the template type name', max_length=30, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='user is active')),
                ('is_deleted', models.BooleanField(default=False, help_text='to delete the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Choose your company name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_template_type_company', to='company.company')),
            ],
        ),
    ]
