# Generated by Django 3.2.16 on 2023-01-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=250)),
                ('start_time', models.CharField(max_length=250)),
                ('end_time', models.CharField(max_length=250)),
                ('timezone', models.CharField(max_length=250)),
                ('innterview_title', models.CharField(max_length=250)),
                ('candidate_email', models.CharField(max_length=250)),
            ],
        ),
    ]
