# Generated by Django 3.2.16 on 2023-01-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingdata',
            old_name='innterview_title',
            new_name='interview_title',
        ),
    ]
