# Generated by Django 3.2.16 on 2023-01-25 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0096_offerletter_start_date_change'),
        ('video_interview', '0002_rename_innterview_title_meetingdata_interview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingdata',
            name='applied_position',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.appliedposition'),
        ),
    ]
