# Generated by Django 3.2.9 on 2021-12-03 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0005_auto_20211203_1026'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='full_name',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='middle_name',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('linked_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('personal_url', models.URLField(blank=True, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='primary_data.address')),
                ('skill', models.ManyToManyField(to='primary_data.KeySkill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
