# Generated by Django 3.2.9 on 2021-12-03 11:48

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0006_auto_20211203_1026'),
        ('user', '0002_auto_20211203_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='phone_otp',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default=None, null=True, upload_to=user.models.upload_user_avatar),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primary_data.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
