# Generated by Django 3.2.9 on 2021-12-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0006_auto_20211203_1026'),
        ('user', '0004_auto_20211203_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(blank=True, to='primary_data.KeySkill'),
        ),
    ]
