# Generated by Django 3.2.9 on 2021-12-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_historicalmedia_media'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalmedia',
            table='media_history',
        ),
    ]
