# Generated by Django 3.2.9 on 2022-01-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_profile_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
