# Generated by Django 3.2.9 on 2022-01-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedia',
            name='field_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='field_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
