# Generated by Django 3.2.9 on 2022-01-13 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary_data', '0014_auto_20220113_0515'),
        ('user', '0015_auto_20220110_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmedia',
            name='can_delete',
            field=models.BooleanField(default=True, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='historicalmedia',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='historicalmedia',
            name='field_name',
            field=models.CharField(blank=True, help_text='Enter field name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmedia',
            name='file_type',
            field=models.CharField(blank=True, help_text='Enter file type', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmedia',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='historicalmedia',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='historicalmedia',
            name='media_file',
            field=models.TextField(blank=True, help_text='Select file', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmedia',
            name='media_file_name',
            field=models.CharField(blank=True, help_text='Enter Media file name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmedia',
            name='profile',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Choose your profile', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='historicalmedia',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='updated time'),
        ),
        migrations.AlterField(
            model_name='media',
            name='can_delete',
            field=models.BooleanField(default=True, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='media',
            name='field_name',
            field=models.CharField(blank=True, help_text='Enter field name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(blank=True, help_text='Enter file type', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Select your prefrences'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(blank=True, help_text='Select file', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_file_name',
            field=models.CharField(blank=True, help_text='Enter Media file name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='profile',
            field=models.ForeignKey(help_text='Choose your profile', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='media',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated time'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, help_text='Tell us about yourself', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(help_text='Enter your Address', on_delete=django.db.models.deletion.CASCADE, to='primary_data.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Add description in Cover letter', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created date and time'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, help_text='Enter your github URL', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linked_url',
            field=models.URLField(blank=True, help_text='Enter your Linkedin URL', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_url',
            field=models.URLField(blank=True, help_text='Enter your personal URL', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, default=None, help_text='Enter your contact number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_otp',
            field=models.CharField(blank=True, help_text='Enter the OTP', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Select tick box'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(blank=True, help_text='Add your skills and ', to='primary_data.KeySkill'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='updated date and time'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='Enter user number', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
