# Generated by Django 3.2.9 on 2022-03-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20220113_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(blank=True, default=None, help_text='Enter User ID', max_length=20, null=True),
        ),
    ]
