# Generated by Django 3.2.9 on 2022-03-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_profile_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_id',
            new_name='employee_id',
        ),
    ]
