# Generated by Django 3.2.9 on 2022-03-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20220315_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='source',
            field=models.CharField(blank=True, default=None, help_text='Enter Source', max_length=20, null=True),
        ),
    ]
