# Generated by Django 3.2.9 on 2022-03-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_profile_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_type',
            field=models.CharField(blank=True, choices=[('fresher', 'fresher'), ('experience', 'experience')], max_length=20, null=True),
        ),
    ]
