# Generated by Django 3.2.13 on 2022-05-17 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_profile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Enter description', max_length=250, null=True)),
                ('type', models.CharField(blank=True, help_text='Enter type', max_length=120, null=True)),
                ('details', models.CharField(blank=True, help_text='Enter Details', max_length=120, null=True)),
                ('redirect', models.CharField(blank=True, max_length=200, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created_time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated time')),
                ('user', models.ForeignKey(help_text='Choose your user', on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
