# Generated by Django 3.2.13 on 2022-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_activitylogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylogs',
            name='type_id',
            field=models.IntegerField(blank=True, help_text='1. Position Approval, 2.Offer Approval, 3. Form Data, 4. Applied Position', null=True),
        ),
    ]
