# Generated by Django 3.2.13 on 2022-06-13 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_activitylogs_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogs',
            name='action_by',
            field=models.ForeignKey(blank=True, help_text='Enter action by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_action_by', to='user.profile'),
        ),
        migrations.AddField(
            model_name='activitylogs',
            name='candidate',
            field=models.ForeignKey(blank=True, help_text='Enter candidate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_candidate', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='activitylogs',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Choose your user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL),
        ),
    ]
