# Generated by Django 3.2.13 on 2022-06-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0047_jobdescriptionimages'),
        ('user', '0026_auto_20220613_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogs',
            name='applied_position',
            field=models.ForeignKey(blank=True, help_text='Enter applied position', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_applied_position', to='form.appliedposition'),
        ),
    ]
