# Generated by Django 3.2.13 on 2022-07-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_activitylogs_applied_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
