# Generated by Django 3.2.13 on 2022-09-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_profile_secondary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encoded_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
