# Generated by Django 3.2.13 on 2022-10-28 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_user_encoded_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='user.profile')),
                ('members', models.ManyToManyField(blank=True, help_text='add team members', related_name='members', to='user.Profile')),
            ],
        ),
    ]
