# Generated by Django 3.2.13 on 2022-11-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_profile_user_refereed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
