# Generated by Django 3.2.13 on 2022-11-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_remove_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
