# Generated by Django 3.2.13 on 2022-11-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_profile_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='manager',
        ),
    ]
