# Generated by Django 3.2.16 on 2022-12-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_company_url'),
        ('primary_data', '0017_alter_university_country'),
        ('user', '0034_remove_profile_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(blank=True, help_text='Enter your Address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='primary_data.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.department'),
        ),
    ]
