# Generated by Django 3.2.16 on 2023-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_answer_customquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquestion',
            name='answer_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customquestion',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
