# Generated by Django 3.2.16 on 2023-01-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20230104_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
