# Generated by Django 3.2.16 on 2023-01-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_customquestion_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquestion',
            name='option',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
