# Generated by Django 3.2.16 on 2023-01-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_customquestion_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customquestion',
            old_name='option',
            new_name='options',
        ),
    ]
