# Generated by Django 3.2.16 on 2023-01-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_rename_option_customquestion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_text', to='user.media')),
            ],
        ),
    ]
