# Generated by Django 3.2.16 on 2023-01-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_mediatext'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatext',
            name='profile',
            field=models.ForeignKey(default=682, on_delete=django.db.models.deletion.CASCADE, related_name='media_text', to='user.profile'),
            preserve_default=False,
        ),
    ]
