# Generated by Django 3.2.16 on 2023-01-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_customquestion_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquestion',
            name='max',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
