# Generated by Django 3.2.16 on 2023-01-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_customquestion_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customquestion',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customquestion',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='CustomQuestion',
        ),
    ]
