# Generated by Django 3.2.16 on 2023-01-30 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_oktastate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPRAcceptence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accpted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created_time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
