# Generated by Django 3.2.16 on 2023-02-25 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_gdpracceptence'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='device',
            field=models.JSONField(default=user.models.default_json),
        ),
        migrations.CreateModel(
            name='DeviceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.JSONField()),
                ('otp', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
