# Generated by Django 3.2.16 on 2023-03-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_auto_20230225_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.TextField(blank=True, help_text='Enter your github URL', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linked_url',
            field=models.TextField(blank=True, help_text='Enter your Linkedin URL', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_url',
            field=models.TextField(blank=True, help_text='Enter your personal URL', null=True),
        ),
    ]
