# Generated by Django 3.2.16 on 2023-06-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_profile_was_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
