# Generated by Django 3.2.16 on 2023-06-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_profile_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='was_candidate',
        ),
    ]
