# Generated by Django 3.2.16 on 2023-06-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_remove_profile_was_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportEmployeeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='importEmployeesFile')),
            ],
        ),
    ]
