# Generated by Django 3.2.16 on 2023-06-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_profile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uuid',
        ),
    ]
