# Generated by Django 3.2.16 on 2023-06-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_remove_profile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='momo',
            field=models.CharField(default='momo', max_length=255),
        ),
    ]
