# Generated by Django 3.2.16 on 2023-06-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_profile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='momo',
        ),
    ]
