# Generated by Django 3.2.9 on 2022-01-07 06:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0009_auto_20211229_0603'),
        ('company', '0002_initial'),
        ('scorecard', '0002_auto_20211231_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeAndCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitage', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['attribute', 'competency', 'company'])),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['competency', 'company'])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_company', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCompetency',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('competency', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['competency', 'company'])),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical competency',
                'db_table': 'competency_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='historicalcategory',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalcategory',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='competency',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='waitage',
        ),
        migrations.RemoveField(
            model_name='historicalattribute',
            name='competency',
        ),
        migrations.RemoveField(
            model_name='historicalattribute',
            name='waitage',
        ),
        migrations.RemoveField(
            model_name='historicalscorecard',
            name='business_acumen',
        ),
        migrations.RemoveField(
            model_name='historicalscorecard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalscorecard',
            name='challenge_agility',
        ),
        migrations.RemoveField(
            model_name='historicalscorecard',
            name='challenge_complexity',
        ),
        migrations.RemoveField(
            model_name='historicalscorecard',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='historicalscorecard',
            name='competency',
        ),
        migrations.RemoveField(
            model_name='historicalscorecard',
            name='drive_performance',
        ),
        migrations.RemoveField(
            model_name='historicalscorecard',
            name='innovative_thinking',
        ),
        migrations.RemoveField(
            model_name='historicalscorecard',
            name='leadership',
        ),
        migrations.RemoveField(
            model_name='historicalscorecard',
            name='social_responsibility',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='business_acumen',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='challenge_agility',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='challenge_complexity',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='competency',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='drive_performance',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='innovative_thinking',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='leadership',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='social_responsibility',
        ),
        migrations.AddField(
            model_name='historicalscorecard',
            name='position',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='form.formdata'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.formdata'),
        ),
        migrations.AlterField(
            model_name='historicalscorecard',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['attribute_and_competency', 'company']),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['attribute_and_competency', 'company']),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='HistoricalCategory',
        ),
        migrations.AddField(
            model_name='attributeandcompetency',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_and_competency_attribute', to='scorecard.attribute'),
        ),
        migrations.AddField(
            model_name='attributeandcompetency',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_and_competency_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='attributeandcompetency',
            name='competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_and_competency_competency', to='scorecard.competency'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='attribute_and_competency',
            field=models.ManyToManyField(blank=True, to='scorecard.AttributeAndCompetency'),
        ),
    ]
