# Generated by Django 3.2.9 on 2022-01-10 08:05

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_auto_20220107_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscorecard',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['card_name', 'company']),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['card_name', 'company']),
        ),
    ]
