# Generated by Django 3.2.9 on 2022-01-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0004_auto_20220110_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscorecard',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalscorecard',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalscorecard',
            name='position',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='attribute_and_competency',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='company',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='position',
        ),
        migrations.AddField(
            model_name='competency',
            name='attribute',
            field=models.ManyToManyField(blank=True, help_text='group attribute to competency', to='scorecard.Attribute'),
        ),
        migrations.DeleteModel(
            name='AttributeAndCompetency',
        ),
        migrations.DeleteModel(
            name='HistoricalScoreCard',
        ),
        migrations.DeleteModel(
            name='ScoreCard',
        ),
    ]
