# Generated by Django 3.2.9 on 2022-03-14 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0028_positionalert_savedposition'),
        ('scorecard', '0006_auto_20220120_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionattribute',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_card_position_attribute', to='form.formdata'),
        ),
    ]
