# Generated by Django 3.2.9 on 2022-03-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0007_alter_positionattribute_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcompetency',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalcompetency',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpositionattribute',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalpositionattribute',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpositionattribute',
            name='position',
        ),
        migrations.DeleteModel(
            name='HistoricalAttribute',
        ),
        migrations.DeleteModel(
            name='HistoricalCompetency',
        ),
        migrations.DeleteModel(
            name='HistoricalPositionAttribute',
        ),
    ]
