# Generated by Django 3.2.13 on 2022-05-09 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0038_alter_reason_type'),
        ('user', '0023_profile_department'),
        ('scorecard', '0008_auto_20220315_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionattribute',
            name='attribute',
        ),
        migrations.CreateModel(
            name='PositionScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Enter rating out of 5')),
                ('comment', models.TextField(blank=True, help_text='scorecard comment', null=True)),
                ('attribute', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.attribute')),
                ('competency', models.ForeignKey(blank=True, help_text='competency list to that specific position', on_delete=django.db.models.deletion.CASCADE, to='scorecard.competency')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formdata')),
                ('profiles', models.ForeignKey(blank=True, help_text='user profile list who are going to interviewing this position stage', on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PositionCompetencyAndAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ManyToManyField(blank=True, to='scorecard.Attribute')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.competency')),
                ('position_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.positionattribute')),
            ],
        ),
    ]
