# Generated by Django 3.2.13 on 2022-05-09 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0038_alter_reason_type'),
        ('scorecard', '0009_auto_20220509_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positioncompetencyandattribute',
            name='position_attribute',
        ),
        migrations.AddField(
            model_name='positioncompetencyandattribute',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='form.formdata'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PositionAttribute',
        ),
    ]
