# Generated by Django 3.2.13 on 2022-05-09 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_profile_department'),
        ('scorecard', '0010_auto_20220509_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionscorecard',
            name='profiles',
        ),
        migrations.AddField(
            model_name='positionscorecard',
            name='applied_profiles',
            field=models.ForeignKey(blank=True, default=1, help_text='user profile list who is applied to that specific position', on_delete=django.db.models.deletion.CASCADE, related_name='position_scorecard_applied_profiles', to='user.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionscorecard',
            name='interviewer_profile',
            field=models.ForeignKey(blank=True, default=1, help_text='user profile list who are going to interviewing this position stage', on_delete=django.db.models.deletion.CASCADE, related_name='position_scorecard_interviewer_profile', to='user.profile'),
            preserve_default=False,
        ),
    ]
