# Generated by Django 3.2.13 on 2022-10-10 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0014_alter_positionscorecard_position_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionscorecard',
            name='competency',
            field=models.ForeignKey(blank=True, help_text='competency list to that specific position', on_delete=django.db.models.deletion.CASCADE, to='scorecard.positioncompetencyandattribute'),
        ),
    ]
