# Generated by Django 3.2.16 on 2022-12-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_alter_shorturl_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='internal',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
