# Generated by Django 3.2.16 on 2023-02-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_shorturl_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
